ecom_project_2/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart-summary'),
    path('add/', views.cart_add, name='cart-add'),
    path('delete/', views.cart_delete, name='cart-delete'),
    path('update/', views.cart_update, name='cart-update'),

]

ecom_project_2/conversation/urls.py
from django.urls import path

from . import views

app_name = "conversation"

urlpatterns = [
    path("", views.inbox, name="inbox"),
    path("new/<int:item_pk>/", views.new_conversation, name="new"),
    path("detail/<int:pk>/", views.detail, name="detail")
]

ecom_project_2/coreApp/urls.py
from django.urls import path

from . import views

app_name = "coreApp"

urlpatterns = [
    path("", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),

    path("add-item/", views.new_item, name="add-item"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("update-product/<int:pk>/", views.update_item, name="update-product"),
    path("delete/<int:pk>/", views.delete, name="delete"),

    path("search/", views.search, name="david"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("manage-shipping/", views.manage_shipping, name="manage-shipping"),

]

ecom_project_2/ecom_project/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("coreApp.urls")),
    path("conversation/", include("conversation.urls")),
    path("cart/", include("cart.urls")),
    path("payment/", include("payment.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecom_project_2/coreApp/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Categories"
        ordering = ["-name"]

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name="products", on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    price = models.IntegerField()

    description = models.TextField()
    is_sold = models.BooleanField(default=False)
    stock = models.IntegerField()

    created_by = models.ForeignKey(User, related_name="products", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    image = models.ImageField(upload_to="images")

    def __str__(self):
        return self.name

ecom_project_2/coreApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Product


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Enter username",
        "class": "form-control"
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        "placeholder": "Enter email",
        "class": "form-control"
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Enter password",
        "class": "form-control"
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Repeat password",
        "class": "form-control"
    }))


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]

    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Enter username",
        "class": "form-control"
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Enter password",
        "class": "form-control"
    }))


# CRUD
class ProductRegisterForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["category", "name", "price", "description",
                  "is_sold", "stock", "image"]

        widgets = {
            "category": forms.Select(attrs={
                "class": "form-control"
            }),

            "name": forms.TextInput(attrs={
                "class": "form-control"
            }),

            "price": forms.TextInput(attrs={
                "class": "form-control"
            }),

            "description": forms.Textarea(attrs={
                "class": "form-control"
            }),

            "is_sold": forms.RadioSelect(attrs={
                "class": "form-control"
            }),

            "image": forms.FileInput(attrs={
                "class": "form-control"
            }),

            "stock": forms.TextInput(attrs={
                "class": "form-control"
            }),
        }

ecom_project_2/coreApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from django.db.models import Q

from django.contrib import messages
from .models import Category, Product
from .forms import UserRegisterForm, UserLoginForm, ProductRegisterForm

from payment.models import ShippingAddress
from payment.forms import ShippingForm


def home(request):
    products = Product.objects.all()

    context = {"products": products}
    return render(request, "coreApp/home.html", context)


def signup(request):
    form = UserRegisterForm()

    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("coreApp:login")

    context = {"form": form}
    return render(request, "coreApp/signup.html", context)


def login_view(request):
    form = UserLoginForm()

    if request.method == "POST":
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("coreApp:home")

    context = {
        "form": form,
    }
    return render(request, "coreApp/login.html", context)


def logout_view(request):
    logout(request)
    return redirect("coreApp:login")


def category(request):
    all_categories = Category.objects.all()
    return {"all_categories": all_categories}


@login_required
def new_item(request):
    form = ProductRegisterForm()

    if request.method == "POST":
        form = ProductRegisterForm(request.POST, request.FILES)  # Because we are adding images from the frontend

        if form.is_valid():
            product = form.save(commit=False)
            product.created_by = request.user
            product.save()

            return redirect("coreApp:home")

    context = {
        "form": form,
        "title": "Add New Item",
    }
    return render(request, "coreApp/new_item.html", context)



def detail(request, pk):
    # product = Product.objects.get(pk=pk)
    product = get_object_or_404(Product, pk=pk)
    related_products = Product.objects.filter(category=product.category).exclude(pk=pk)


    context = {
        "product": product,
        "related_products": related_products,
    }
    return render(request, "coreApp/item_detail.html", context)



@login_required
def update_item(request, pk):
    # product = Product.objects.get(pk=pk, created_by=request.user)
    product = get_object_or_404(Product, pk=pk, created_by=request.user)

    form = ProductRegisterForm(instance=product)

    if request.method == "POST":
        form = ProductRegisterForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect("coreApp:home")

    context = {
        "title": "Edit Product",
        "form": form,
    }
    return render(request, "coreApp/new_item.html", context)


@login_required
def delete(request, pk):
    product = get_object_or_404(Product, pk=pk, created_by=request.user)

    if request.method == "POST":
        product.delete()
        return redirect("coreApp:home")

    context = {"product": product}
    return render(request, "coreApp/delete.html", context)


def search(request):
    query = request.GET.get("query", "")
    products = Product.objects.filter(is_sold=False)

    if query:
        products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))

    context = {
        "query": query,
        "products": products
    }
    return render(request, "coreApp/search.html", context)


def dashboard(request):
    products = Product.objects.filter(created_by=request.user)

    context = {
        "products": products
    }
    return render(request, "coreApp/dashboard.html", context)


@login_required(login_url='my-login')
def manage_shipping(request):
    try:
        # Account user with shipment information
        shipping = ShippingAddress.objects.get(user=request.user.id)
    except ShippingAddress.DoesNotExist:
        # Account user with no shipment information
        shipping = None

    form = ShippingForm(instance=shipping)
    if request.method == 'POST':
        form = ShippingForm(request.POST, instance=shipping)
        if form.is_valid():
            # Assign the user FK on the object
            shipping_user = form.save(commit=False)
            # Adding the FK itself
            shipping_user.user = request.user

            shipping_user.save()
            messages.info(request, "Update success!")
            return redirect('coreApp:dashboard')
    context = {'form': form}
    return render(request, 'coreApp/manage_shipping.html', context)

ecom_project_2/coreApp/templates/coreApp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <title>{% block title %}{% endblock title %} | MyApp©</title>-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css" integrity="sha384-3B6NwesSXE7YJlcLI9RpRqGf2p/EgVH8BgoKTaUrmKNDkHPStTQ3EyoYjCGXaOTS" crossorigin="anonymous" />    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


    <!--Google symbols -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet">

    <!--Jquery CDN -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
</head>
<body>
  <body>
      <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
      <div class="container-fluid container">
        <a class="navbar-brand" href="{% url 'coreApp:home' %}">My Ecom Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Category
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">All</a></li>

                {% for category in all_categories %}-->
                <li><a class="dropdown-item" href="#">{{ category.name }}</a></li>
                {% endfor %}
              </ul>
            </li>


            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'coreApp:add-item' %}">Add item</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'conversation:inbox' %}">Inbox</a>
            </li>
<!--             <li class="nav-item">-->
<!--              <a class="nav-link" href="{% url 'conversation:inbox' %}">Inbox</a>-->
<!--            </li>-->
            <li class="nav-item">
              <a class="nav-link" href="{% url 'coreApp:dashboard' %}">@{{ request.user }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'coreApp:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'coreApp:signup' %}">Signup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'coreApp:login' %}">Login</a>
            </li>
            {% endif %}
          </ul>

          <form class="d-flex" role="search" action="{% url 'coreApp:david' %}">
            <input class="form-control me-2" name="query" value="{{ query }}" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
<!--CART START -->
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a href="{% url 'cart:cart-summary' %}" class="btn btn-outline-warning">
              Cart
              <span id="cart-qty" class="text-white">
                {% with qty_amount=cart|length %}
                  {% if qty_amount > 0 %}
                    {{ qty_amount }}
                  {% else %}
                    0
                  {% endif %}

                {% endwith %}
              </span>
            </a>
        </li>
      </ul>
      <!--CART END-->

        </div>
      </div>
    </nav>

      <div class="container">
          {% block content %}{% endblock content %}
      </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

ecom_project_2/coreApp/templates/coreApp/dashboard.html
{% extends "coreApp/base.html" %}

{% block title %}Dashboard{% endblock title %}

{% block content %}

<h1 class="mt-5">@{{ request.user.username|capfirst }}'s Dashboard</h1>


<main role="main" class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
        {% for product in products %}
        <div class="col">
            <div class="card shadow-sm">
                <img src="{{ product.image.url }}" alt="" width="100%" height="225">
                <div class="card-body bg-dark text-white">
                    <p class="card-text">{{ product.name }}</p>
                    <p class="card-text">${{ product.price }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'coreApp:detail' product.id %}" type="button"
                               class="btn btn-sm btn-outline-success">View</a>
                            <a href="{% url 'coreApp:update-product' product.id %}" type="button"
                               class="btn btn-sm btn-outline-secondary text-white">Edit</a>
                            <a href="{% url 'coreApp:delete' product.id %}" type="button"
                               class="btn btn-sm btn-outline-danger">Delete</a>
                            <!-- add to cart and take the user to checkout page-->
                        </div>
                        <small class="text-body-secondary"></small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <br>



<div class="container bg-white shadow-md p-5 form-layout">
    <h4> <i class="fa fa-chevron-circle-right" aria-hidden="true"></i> &nbsp; Manage shipping </h4>
    <hr>

    <p> Enter in a shipping address </p>
    <a class="btn btn-primary navbar-btn text-white" type="button"  href="{% url 'coreApp:manage-shipping' %}"> Manage shipping </a>
</div>
<br>
</div>

Vince, [7/25/2024 4:48 PM]
PayPals="btn btn-primary navbar-btn text-white" type="button"  href="{% url 'coreApp:manage-shipping' %}"> Manage shipping </a>
</div>
<br>
</div>
</main>
{% endblock content %}

ecom_project_2/coreApp/templates/coreApp/delete.html
{% extends "coreApp/base.html" %}

{% block title %}Delete{% endblock title %}

{% block content %}
<h1>Delete</h1>
    <form action="" method="POST">
        {% csrf_token %}

        <p class="my-5">Are you sure that you want to delete {{ product.name }}?</p>

        <a href="{% url 'coreApp:home' %}" class="btn btn-success">Back</a>
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
    </form>

{% endblock content %}

ecom_project_2/coreApp/templates/coreApp/form.html
<div class="container mt-5">
    <div class="col-lg-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <h1 class="mb-4 text-center">title</h1>

                <form method="post" action=".">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label class="form-label">Category</label>
                        {{ form.category }}
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Name</label>
                        {{ form.name }}
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Price</label>
                        {{ form.price }}
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Description</label>
                        {{ form.description }}
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Image</label>
                        {{ form.image }}
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Stock</label>
                        {{ form.stock }}
                    </div>

                    <button type="submit" class="btn btn-success btn-lg btn-block">title </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

ecom_project_2/coreApp/templates/coreApp/home.html
{% extends "coreApp/base.html" %}
{% load static %}
{% block title %}Home{% endblock title %}

{% block content %}
<h1>Home page</h1>

<section>
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for item in products %}
            <div class="col">
                <div class="card h-100">
                  <img src="{{ item.image.url }}" class="card-img-top" alt="..." width="100%" height="255">
                  <div class="card-body">
                    <h5 class="card-title">{{ item.name }}</h5>
                    <p class="card-text">{{ item.price }}</p>
                    <a href="{% url 'coreApp:detail' item.id %}" class="btn btn-secondary">View</a>
                    <p class="card-text">{{ item.id }}</p>
                  </div>
                </div>
              </div>
        {% endfor %}
    </div>
</div>
</section>

{% endblock content %}

ecom_project_2/coreApp/templates/coreApp/item_detail.html
{% extends 'coreApp/base.html' %}

{% block title %}Signup{% endblock title %}

{% block content %}

<h1>{{product.name}} Detail</h1>

<div class="py-5 bg-body-secondary rounded">
 <div class="container">
   <div class="row mx-5">
     <div class="col-md-8">
       <img src="{{product.image.url}}" class="img-fluid rounded" width="100%">
     </div>
     <div class="col-md-4">
        <!-- Add more details about the item here -->
        <h2>{{product.name}}</h2>
         <br>
        <p><strong>Price: </strong> ₦ {{product.price}}</p>
         <p>ID: {{product.id}} </p>
        <p><strong>Description:</strong><br>
        </p>{{product.description}}</p>
         <br>
        <p><strong>Vendor: </strong>@{{product.created_by.username}}</p>
        <!-- if the requesting user is the product owner-->
         {% if request.user == product.created_by %}
             <a href="{% url 'coreApp:update-product' product.id %}" type="button" class="btn btn-md btn-outline-success">Edit</a>
             <a href="delete item" type="button" class="btn btn-md btn-outline-danger">Delete</a>

         <!-- otherwise -->
         {% else %}
        <div class="row justify-content-start">
            <div class="col-md-8">Select Quantity:</div>
            <div class="col-md-8">
            <select class="form-select" id="select">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select>
            </div>
        </div>

        <br><br>

         <a href="{% url 'conversation:new' product.id %}" class="btn btn-secondary">Contact Seller</a>
         <button type="button" value="{{ product.id }}" class="btn btn-success" id="add-button">Add to Cart</button>

         <!-- end here -->
         {% endif %}
        </div>
     </div>
   </div>
 </div>
    <br>
    <hr>
    <br>
    <h1 class="">Related Items</h1>
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
             {% if related_products %}
                {% for product in related_products %}
                <div class="col">
                <div class="card shadow-sm">
                    <img src="{{product.image.url}}" alt="" width="100%" height="225">
                    <div class="card-body">
                        <p class="card-text"> {{product.name}}</p>
                        <p class="card-text">$ {{product.price}}</p>
                        <p class="card-text"><strong>Category: </strong>{{product.category.name}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">

                                {% if request.user == product.created_by %}
                                <a href="products detail with pk" type="button"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                <a href="{% url 'coreApp:update-product' product.id %}" type="button" class="btn btn-sm btn-outline-success">Edit</a>
                                <a href="products delete' with pk" type="button" class="btn btn-sm btn-outline-danger">Delete</a>
                                {% else %}
                                <a href="{% url 'coreApp:detail' product.id %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Buy Now</button>
                                <a href="conversation new with pk" type="button"
                                   class="btn btn-sm btn-outline-secondary">Contact Seller</a>
                                <!-- add to cart and take the user to check-out page-->
                                {% endif %}
                            </div>
                            <small class="text-body-secondary">@ {{product.created_by.username}} </small>
                        </div>
                    </div>
                </div>
            </div>
                 {% endfor %}
            {% else %}
                <p>There are no related items for {{ product.category.name }} category</p>
            {% endif %}
        </div>
    </div>
</div>

<!--AJAX Starts Here-->
<script>
    // Add button

    $(document).on('click', '#add-button', function(e){
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart-add" %}',
            data: {
                product_id: $('#add-button').val(),
                product_quantity: $("#select option:selected").text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },

            success: function(json){

                //console.log(json)

                //Sets the text content of the cart-qty in base.html
                //test to see if our cart adjusts automatically. remove the 0 for now.
                document.getElementById("cart-qty").textContent = json.qty
            },

            error: function(xhr, errmsg, err){

            }
        });
    })

    // Add button 2
    $(document).on('click', '.add-button', function(e){
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart-add" %}',
            data: {
                product_id: $('.add-button').val(),
                product_quantity: $("#select option:selected").text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },

            success: function(json){

                //console.log(json)

                //Sets the text content of the cart-qty in base.html
                //test to see if our cart adjusts automatically. remove the 0 for now.
                document.getElementById("cart-qty").textContent = json.qty
            },

            error: function(xhr, errmsg, err){

            }
        });
    })
</script>

{% endblock content %}

ecom_project_2/coreApp/templates/coreApp/login.html
{% extends 'coreApp/base.html' %}

{% block title %}Login{% endblock title %}

{% block content %}

<div class="container mt-5">
    <div class="col-lg-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <h1 class="mb-4 text-center">Login</h1>

                <form method="post" action=".">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label class="form-label">Username</label>
                        {{ form.username }}
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Enter Password</label>
                        {{ form.password }}
                    </div>

                    <button type="submit" class="btn btn-success btn-lg btn-block">Login</button>
                </form>
                <br>
                <div><small>Dont have an account? <a href="{% url 'coreApp:signup' %}" class="text-decoration-none">Signup</a></small></div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

ecom_project_2/coreApp/templates/coreApp/manage_shipping.html
{% extends "coreApp/base.html" %}

{% load static %}

{% load crispy_forms_tags %}



{% block content %}

    <style>


        body{


            background-color: gray;

        }



    </style>

    <body>

        <br>

        <div class="container bg-white shadow-md p-5 form-layout">

            <h3> <i class="fa fa-chevron-circle-right" aria-hidden="true"></i> &nbsp; Manage shipping </h3>

            <p> Please fill in your shipping address. </p>

            <hr>

            <br>

            <form method="POST" autocomplete="off">

                {% csrf_token %}

                {{form.full_name|as_crispy_field}}


                <br>


                {{form.email|as_crispy_field}}

                <br>

                {{form.address1|as_crispy_field}}

                <br>


                {{form.address2|as_crispy_field}}


                <br>

                {{form.city|as_crispy_field}}


                <br>


                {{form.state|as_crispy_field}}


                <br>




                {{form.zipcode|as_crispy_field}}


                <br>


                <button type="submit" class="btn btn-primary navbar-btn text-white w-100 p-2"> Update shipping address </button>



            </form>



        </div>



    </body>

    <br> <br>


{% endblock %}

ecom_project_2/coreApp/templates/coreApp/search.html
{% extends "coreApp/base.html" %}

{% block title %}Search{% endblock title %}

{% block content %}
<h1>Find Items</h1>

<div class="py-5 bg-body-tertiary">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <!-- looping over the item -->
            {% if products %}
                {% for product in products %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="{{ product.image.url }}" alt="" width="100%" height="225">
                        <div class="card-body">
                            <p class="card-text"> {{ product.name }} </p>
                            <p class="card-text">$ {{ product.price }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'coreApp:detail' product.id %}" type="button"
                                       class="btn btn-sm btn-outline-secondary">View</a>
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Buy Now</button>
                                    <!-- add to cart and take the user to checkout page-->
                                </div>
                                <small class="text-body-secondary">@ {{ product.created_by.username }} </small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <!-- endfor -->
            {% else %}
            <p>No product was found</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}