ecom_project_2/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart-summary'),
    path('add/', views.cart_add, name='cart-add'),
    path('delete/', views.cart_delete, name='cart-delete'),
    path('update/', views.cart_update, name='cart-update'),

]

ecom_project_2/ecom_project/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("coreApp.urls")),
    path("conversation/", include("conversation.urls")),
    path("cart/", include("cart.urls")),
    path("payment/", include("payment.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecom_project_2/payment/urls.py
from django.urls import path

from . import views

app_name = "payment"

urlpatterns = [
    path("", views.checkout, name="checkout"),
    path("complete-order", views.complete_order, name="complete-order"),
    path("payment-success", views.payment_success, name="payment-success"),
    path("payment-failed", views.payment_failed, name="payment-failed"),

]

ecom_project_2/payment/models.py
from django.db import models

from django.contrib.auth.models import User

from coreApp.models import Product


class ShippingAddress(models.Model):
    full_name = models.CharField(max_length=300)

    email = models.EmailField(max_length=255)

    address1 = models.CharField(max_length=300)

    address2 = models.CharField(max_length=300)

    city = models.CharField(max_length=255)

    # Optional

    state = models.CharField(max_length=255, null=True, blank=True)

    zipcode = models.CharField(max_length=255, null=True, blank=True)

    # FK

    # Authenticated / not authenticated users (bear in mind)

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Shipping Address'

    def __str__(self):
        return 'Shipping Address - ' + str(self.id)


class Order(models.Model):
    full_name = models.CharField(max_length=300)

    email = models.EmailField(max_length=255)

    shipping_address = models.TextField(max_length=10000)

    amount_paid = models.DecimalField(max_digits=8, decimal_places=2)

    date_ordered = models.DateTimeField(auto_now_add=True)

    # FK

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return 'Order - #' + str(self.id)


class OrderItem(models.Model):
    # FK ->

    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)

    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)

    quantity = models.PositiveBigIntegerField(default=1)

    price = models.DecimalField(max_digits=8, decimal_places=2)

    # FK

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return 'Order Item - #' + str(self.id)

ecom_project_2/payment/forms.py
from django import forms

from .models import ShippingAddress


class ShippingForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields = ["full_name", "email", "address1", "address2", "city", "state", "zipcode", "user"]

        exclude = ["user"]

ecom_project_2/payment/views.py
from django.http import JsonResponse
from django.shortcuts import render

from .models import ShippingAddress, Order, OrderItem
from cart.cart import Cart


def checkout(request):
    # Users with accounts -- Pre-fill the form

    if request.user.is_authenticated:

        try:

            # Authenticated users WITH shipping information

            shipping_address = ShippingAddress.objects.get(user=request.user.id)

            context = {'shipping': shipping_address}

            return render(request, 'payment/checkout.html', context=context)

        except:
            return render(request, 'payment/checkout.html')

    else:

        # Guest users

        return render(request, 'payment/checkout.html')


def complete_order(request):
    if request.POST.get('action') == 'post':

        name = request.POST.get('name')
        email = request.POST.get('email')

        address1 = request.POST.get('address1')
        address2 = request.POST.get('address2')
        city = request.POST.get('city')

        state = request.POST.get('state')
        zipcode = request.POST.get('zipcode')

        # All-in-one shipping address

        shipping_address = (address1 + "\n" + address2 + "\n" +

                            city + "\n" + state + "\n" + zipcode

                            )

        # Shopping cart information

        cart = Cart(request)

        # Get the total price of items

        total_cost = cart.get_total()

        '''

            Order variations

            1) Create order -> Account users WITH + WITHOUT shipping information


            2) Create order -> Guest users without an account


        '''

        # 1) Create order -> Account users WITH + WITHOUT shipping information

        if request.user.is_authenticated:

            order = Order.objects.create(full_name=name, email=email, shipping_address=shipping_address,

                                         amount_paid=total_cost, user=request.user)

            order_id = order.pk

            for item in cart:
                OrderItem.objects.create(order_id=order_id, product=item['product'], quantity=item['qty'],

                                         price=item['price'], user=request.user)


        #  2) Create order -> Guest users without an account

        else:

            order = Order.objects.create(full_name=name, email=email, shipping_address=shipping_address,

                                         amount_paid=total_cost)

            order_id = order.pk

            for item in cart:
                OrderItem.objects.create(order_id=order_id, product=item['product'], quantity=item['qty'],

                                         price=item['price'])

        order_success = True

        response = JsonResponse({'success': order_success})

        return response


def payment_success(request):
    # Clear shopping cart

    for key in list(request.session.keys()):

        if key == 'session_key':
            del request.session[key]

    return render(request, 'payment/payment_success.html')


def payment_failed(request):
    context = {}
    return render(request, "payment/payment_failed.html", context)

ecom_project_2/payment/templates/payment/checkout.html
{% include "coreApp/base.html" %}


{% load static %}


{% block content %}

<style>

    body
    {

        background-color: gray;

    }


</style>


    <body>

        <br>

        <div class="container bg-white shadow-md p-5" style="width:500px; border-radius:20px;">

            <form id="form" onsubmit="event.preventDefault();">

                <div>

                    <h3> <i class="fa fa-chevron-circle-right" aria-hidden="true"></i> &nbsp; Complete your order </h3>

                    <p> Please enter in the relevant information below. </p>



                    <hr>

                    <br>

                    <div class="form-field">

                        <input class="form-control validate" id="name" type="text" placeholder="Full name*" autocomplete="off" value="{{shipping.full_name}}" required>

                    </div>


                    <br>


                    <div class="form-field">

                        <input class="form-control validate" id="email" type="email" placeholder="Email address*" autocomplete="off" value="{{shipping.email}}" required>

                    </div>


                    <br>


                    <div class="form-field">

                        <input class="form-control validate" id="address1" type="text" placeholder="Address 1*" autocomplete="off" value="{{shipping.address1}}" required>

                    </div>


                    <br>


                    <div class="form-field">

                        <input class="form-control validate" id="address2" type="text" placeholder="Address 2*" autocomplete="off" value="{{shipping.address2}}" required>

                    </div>


                    <br>


                    <div class="form-field">

                        <input class="form-control validate" id="city" type="text" placeholder="City*" autocomplete="off" value="{{shipping.city}}" required>

                    </div>


                    <br>


                    <div class="form-field">

                        <input class="form-control" id="state" type="text" placeholder="State (Optional)" autocomplete="off" value="{{shipping.state}}">

                    </div>


                    <br>


                    <div class="form-field">

                        <input class="form-control" id="zipcode" type="text" placeholder="Zip code (Optional)" autocomplete="off" value="{{shipping.zipcode}}">

                    </div>

                </div>

                <br>



               <!-- <button id="complete-order" class="btn btn-primary navbar-btn text-white"> &nbsp; Complete order </button>
               -->

                <br>


                <div id="paypal-button-container"></div>


                <script src="https://www.paypal.com/sdk/js?client-id=AbzVlgrDdkoYCeoyyh9LMTFZLx20feOnjm6VI9E0HNbpTuIWPEhtkNfnUIg5UtS7ULouzd2eSql8zVED&currency=USD&intent=capture&enable-funding=venmo" data-sdk-integration-source="integrationbuilder"></script>



            </form>


        </div>



        <br>


    </body>


     <!-- Ajax integration -->



    <script>

    // Total price

    var total_price = '{{cart.get_total}}';


    // PayPal Script

    const paypalButtonsComponent = paypal.Buttons({
        // optional styling for buttons
        // https://developer.paypal.com/docs/checkout/standard/customize/buttons-style-guide/
        style: {
          color: "blue",
          shape: "pill",
          layout: "vertical",
        },

        onInit: function(data, actions) {

            actions.disable();


            // Complete order - NO SHIPPING

            document.querySelectorAll('.validate').forEach(item => {
                item.addEventListener('keyup', event => {

                    //  The required fields are filled out

                    var order_verified = 'Yes';

                    function checkInputs(){

                        $(':input[required]').each(function(){

                            if($(this).val() == ''){

                                // The required fields are empty

                                return order_verified = 'No';

                            }

                        });

                        return order_verified;

                    }


                    var isOrderVerified = checkInputs()


                    if(isOrderVerified === 'Yes')
                    {

                        actions.enable();

                    }

                    else

                    {
                        actions.disable();

                    }

                });

            });


             // Complete order - WITH SHIPPING


             //  The required fields are filled out

             var order_verified = 'Yes';

             function checkInputs(){

                 $(':input[required]').each(function(){

                     if($(this).val() == ''){


                         // The required fields are empty

                        return order_verified = 'No';

                    }

                });

                return order_verified;

             }

             var isOrderVerified = checkInputs()

             if(isOrderVerified === 'Yes')
             {

                actions.enable();

             }

             else
             {

                actions.disable();

             }

        },


        // set up the transaction
        createOrder: (data, actions) => {
            // pass in any options from the v2 orders create call:
            // https://developer.paypal.com/api/orders/v2/#orders-create-request-body
            const createOrderPayload = {
                purchase_units: [
                    {
                        amount: {
                            value: total_price
                        }
                    }
                ]
            };

            return actions.order.create(createOrderPayload);
        },


        // finalize the transaction
        onApprove: (data, actions) => {
            const captureOrderHandler = (details) => {

                const payerName = details.payer.name.given_name;

                console.log('Transaction completed');


                // Ajax functionality

                $.ajax({

                    type: 'POST',
                    url: '{% url "payment:complete-order" %}',
                    data: {

                        name: $('#name').val(),
                        email: $('#email').val(),

                        address1: $('#address1').val(),
                        address2: $('#address2').val(),
                        city: $('#city').val(),

                        state: $('#state').val(),
                        zipcode: $('#zipcode').val(),


                        csrfmiddlewaretoken: "{{csrf_token}}",
                        action: 'post'

                    },

                    success: function(json){

                        //console.log(json)

                        window.location.replace("{% url 'payment:payment-success' %}");


                    },

                    error: function(xhr, errmsg, err){

                        window.location.replace("{% url 'payment:payment-failed' %}");

                    }

                });


            };

            return actions.order.capture().then(captureOrderHandler);
        },



        // handle unrecoverable errors
        onError: (err) => {
            console.error('An error prevented the buyer from checking out with PayPal');
        }
    });


    paypalButtonsComponent
        .render("#paypal-button-container")
        .catch((err) => {
            console.error('PayPal Buttons failed to render');
        });




   </script>





{% endblock %}

ecom_project_2/payment/templates/payment/payment_failed.html
<h1> </h1>
{% include "coreApp/base.html" %}

{% load static %}

{% block content %}

<style>


    body{


        background-color: white;

    }



</style>

<body>

    <br>

    <div class="container bg-white shadow-md p-5 form-layout">

        <div class="text-center">

            <i class="text-danger fa fa-credit-card-alt fa-3x" aria-hidden="true"></i>

            <br> <br>


            <h5> <strong> YOU NO GET MONET! </strong> </h5>

            <hr>

            <p> Your order was not processed. </p>


        </div>


    </div>


</body>


{% endblock %}

ecom_project_2/payment/templates/payment/payment_success.html
<h1></h1>

{% include "coreApp/base.html" %}

{% load static %}

{% block content %}

<style>


    body{


        background-color: white;

    }



</style>

<body>

    <br>

    <div class="container bg-white shadow-md p-5 form-layout">

        <div class="text-center">

            <i class="text-success fa fa-credit-card-alt fa-3x" aria-hidden="true"></i>

            <br> <br>


            <h5> <strong> Payment success! </strong> </h5>

            <hr>

            <p> you get money. </p>


        </div>


    </div>


</body>


{% endblock %}